spring:
  application:
    name: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: orderQueue
    exchange: orderExchange
    routing-key: orderRoutingKey

  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



